// Mock data interface
export type TableData = {
  id: number;
  name: string;
  email: string;
  age: number;
  company: string;
};

// Mock data generation
export const generateMockData = (): TableData[] => {
  return [
    {
      id: 1,
      name: "Raj Patel",
      email: "raj.patel@techsolutions.com",
      age: 28,
      company: "Infosys Technologies",
    },
    {
      id: 2,
      name: "Priya Sharma",
      email: "priya.sharma@innovate.in",
      age: 35,
      company: "Tata Consultancy Services",
    },
    {
      id: 3,
      name: "Amit Kumar",
      email: "amit.kumar@globaltech.com",
      age: 42,
      company: "Wipro Limited",
    },
    {
      id: 4,
      name: "Neha Gupta",
      email: "neha.gupta@softworld.in",
      age: 31,
      company: "Cognizant Technology Solutions",
    },
    {
      id: 5,
      name: "Suresh Reddy",
      email: "suresh.reddy@enterprisetech.com",
      age: 45,
      company: "HCL Technologies",
    },
    {
      id: 6,
      name: "Anjali Desai",
      email: "anjali.desai@digitalindia.com",
      age: 29,
      company: "Tech Mahindra",
    },
    {
      id: 7,
      name: "Vikram Singh",
      email: "vikram.singh@innovationsync.in",
      age: 37,
      company: "Persistent Systems",
    },
    {
      id: 8,
      name: "Deepa Mehta",
      email: "deepa.mehta@softwaresolutions.com",
      age: 33,
      company: "Mindtree Limited",
    },
    {
      id: 9,
      name: "Rahul Joshi",
      email: "rahul.joshi@globalservices.in",
      age: 40,
      company: "Accenture India",
    },
    {
      id: 10,
      name: "Kavya Krishnamurthy",
      email: "kavya.k@startupsphere.com",
      age: 26,
      company: "Zoho Corporation",
    },
    {
      id: 11,
      name: "Arun Nair",
      email: "arun.nair@cloudtech.in",
      age: 34,
      company: "Mphasis",
    },
    {
      id: 12,
      name: "Sonia Bose",
      email: "sonia.bose@datadynamics.com",
      age: 39,
      company: "IBM India",
    },
    {
      id: 13,
      name: "Vishal Malhotra",
      email: "vishal.malhotra@nextgen.in",
      age: 32,
      company: "Capgemini India",
    },
    {
      id: 14,
      name: "Lakshmi Narayanan",
      email: "lakshmi.n@smartsolutions.com",
      age: 44,
      company: "Oracle Financial Services",
    },
    {
      id: 15,
      name: "Rohan Khanna",
      email: "rohan.khanna@innovatech.in",
      age: 27,
      company: "Infosys BPM",
    },
    {
      id: 16,
      name: "Meera Iyer",
      email: "meera.iyer@digitalworks.com",
      age: 36,
      company: "Wipro Digital",
    },
    {
      id: 17,
      name: "Sanjay Gupta",
      email: "sanjay.gupta@globalinnovations.in",
      age: 41,
      company: "L&T Infotech",
    },
    {
      id: 18,
      name: "Divya Ramachandran",
      email: "divya.ram@techfrontiers.com",
      age: 30,
      company: "Microsoft India",
    },
    {
      id: 19,
      name: "Kartik Subramanian",
      email: "kartik.sub@cloudservices.in",
      age: 38,
      company: "Google India",
    },
    {
      id: 20,
      name: "Pooja Hegde",
      email: "pooja.hegde@smartech.com",
      age: 25,
      company: "Amazon India",
    },
    {
      id: 21,
      name: "Nikhil Tripathi",
      email: "nikhil.tripathi@innovaserve.in",
      age: 33,
      company: "Infosys",
    },
    {
      id: 22,
      name: "Shreya Kulkarni",
      email: "shreya.kulkarni@techwave.com",
      age: 29,
      company: "Tata Technologies",
    },
    {
      id: 23,
      name: "Ajay Mehta",
      email: "ajay.mehta@globalconnect.in",
      age: 42,
      company: "Cognizant",
    },
    {
      id: 24,
      name: "Nisha Pillai",
      email: "nisha.pillai@datainsight.com",
      age: 35,
      company: "HCL Enterprise",
    },
    {
      id: 25,
      name: "Karthik Raman",
      email: "karthik.raman@softlogic.in",
      age: 37,
      company: "Tech Mahindra",
    },
    {
      id: 26,
      name: "Aarti Bhargava",
      email: "aarti.bhargava@innovatech.com",
      age: 31,
      company: "Wipro",
    },
    {
      id: 27,
      name: "Rajesh Pandey",
      email: "rajesh.pandey@cloudnative.in",
      age: 40,
      company: "Persistent Systems",
    },
    {
      id: 28,
      name: "Swathi Narayan",
      email: "swathi.narayan@digitaledge.com",
      age: 28,
      company: "Mindtree",
    },
    {
      id: 29,
      name: "Vikram Rathore",
      email: "vikram.rathore@techsolutions.in",
      age: 36,
      company: "Accenture",
    },
    {
      id: 30,
      name: "Rekha Srinivasan",
      email: "rekha.srinivasan@innovaserve.com",
      age: 39,
      company: "Zoho",
    },
    {
      id: 31,
      name: "Manish Verma",
      email: "manish.verma@globaltech.in",
      age: 34,
      company: "IBM",
    },
    {
      id: 32,
      name: "Ananya Chatterjee",
      email: "ananya.chatterjee@smartsystems.com",
      age: 27,
      company: "Capgemini",
    },
    {
      id: 33,
      name: "Vivek Sharma",
      email: "vivek.sharma@dataworks.in",
      age: 41,
      company: "Oracle",
    },
    {
      id: 34,
      name: "Pallavi Iyer",
      email: "pallavi.iyer@techfrontier.com",
      age: 32,
      company: "Microsoft",
    },
    {
      id: 35,
      name: "Arjun Malhotra",
      email: "arjun.malhotra@innovaconnect.in",
      age: 38,
      company: "Google",
    },
    {
      id: 36,
      name: "Shreya Nambiar",
      email: "shreya.nambiar@cloudservices.com",
      age: 30,
      company: "Amazon Web Services",
    },
    {
      id: 37,
      name: "Rohit Khullar",
      email: "rohit.khullar@digitalinnovations.in",
      age: 35,
      company: "Infosys Technologies",
    },
    {
      id: 38,
      name: "Priyanka Bhatnagar",
      email: "priyanka.bhatnagar@techsync.com",
      age: 33,
      company: "Tata Consultancy",
    },
    {
      id: 39,
      name: "Samir Kapoor",
      email: "samir.kapoor@globalinnovate.in",
      age: 40,
      company: "Wipro Digital",
    },
    {
      id: 40,
      name: "Deepika Rajagopal",
      email: "deepika.rajagopal@softwaresolutions.com",
      age: 29,
      company: "HCL Technologies",
    },
    {
      id: 41,
      name: "Naresh Kumar",
      email: "naresh.kumar@enterprisetech.in",
      age: 42,
      company: "Tech Mahindra",
    },
    {
      id: 42,
      name: "Indira Patel",
      email: "indira.patel@innovationhub.com",
      age: 36,
      company: "Cognizant",
    },
    {
      id: 43,
      name: "Sameer Deshmukh",
      email: "sameer.deshmukh@cloudnative.in",
      age: 37,
      company: "Persistent Systems",
    },
    {
      id: 44,
      name: "Kavita Menon",
      email: "kavita.menon@techwave.com",
      age: 31,
      company: "Mindtree Limited",
    },
    {
      id: 45,
      name: "Ravi Shankar",
      email: "ravi.shankar@globalservices.in",
      age: 39,
      company: "Accenture India",
    },
    {
      id: 46,
      name: "Aditi Rawal",
      email: "aditi.rawal@smarttech.com",
      age: 28,
      company: "Zoho Corporation",
    },
    {
      id: 47,
      name: "Rahul Hegde",
      email: "rahul.hegde@digitalworks.in",
      age: 34,
      company: "IBM India",
    },
    {
      id: 48,
      name: "Shalini Goyal",
      email: "shalini.goyal@innovatech.com",
      age: 32,
      company: "Oracle Financial Services",
    },
    {
      id: 49,
      name: "Amit Singhania",
      email: "amit.singhania@techsolutions.in",
      age: 41,
      company: "Capgemini",
    },
    {
      id: 50,
      name: "Gita Krishnamurthy",
      email: "gita.krishnamurthy@globalinnovations.com",
      age: 37,
      company: "L&T Infotech",
    },
  ];
};
